### PR TITLE
Feature/sqlfiles

### PR DESCRIPTION
**Pull request by abdulmojeed**
check the new page created using bootstrap

### CODE REVIEW

**Comment by Muizudeen** [comment]
Please grant me Write Access to your Repository so I can merge your Pull
Requests.

Thanks

**Comment by abdulmojeed** [comment]
I have added you as collaborator.

thank you,

**Comment by Muizudeen** [comment]
Thanks

**Comment by abdulmojeed** [comment]
I have gotten my new system, installed VMWare, Ubuntu and Git.
unfortunately, I could not continue on the new machine because I have tried
several options to migrate my files from the old machine. I read about
clone, but it did not work too. What is the ideal way of moving files so
that I can continue on the new machine.

**Pull request merged**
